INSERT INTO Roles (ID, TYPE_ROLE) VALUES (0., 'USER');
INSERT INTO Roles (ID, TYPE_ROLE) VALUES (1., 'ADMIN');

INSERT INTO Users (ID, USERNAME, PASSWORD, ROLE_ID) VALUES (0, 'admin', '$2a$10$fKS8m5wqtKmi6BtjHV/mFuxrFARo/blcsKO8BriN4EImAbMEA1/Ue', 1);

